%-------------------------------------Licensing and fair use notice---------------------------------------
%---------------------------------------------------------------------------------------------------------
%This code file forms part of the SquidLab software, University of Warwick and University of Cambridge
%SquidLab remains the intellectual property of the Universities of Warwick and Cambridge, but is freely
%distributed under an Academic Use license for non-commercial use. The license file is included with the
%code files when downloaded, and must always be kept with them if distributed. Please also credit the
%authors if the software contributes to any research results. Please read and make sure you agree with
%the points in the (short) license document. In brief, you may use and also modify any of the code files
%for non-commerical purposes, and should contact Warwick Ventures at the University of Warwick with any
%questions as to potential commercial or profit-making use.
%And remember, we can't guarantee that the software is bug or error free! Make sure to check any results.
%---------------------------------------------------------------------------------------------------------

classdef S700X_Raw_MvH < squidlab.import.ImportPipeline
    %Import pipeline for a .dat file generated by a Cryogenic Inc. S700X
    %Magnetometer. The instrument generates binary files (.dat and .wat).
    %containing the raw position/voltage data - the dat file is converted
    %by this plugin. The first operation of this plugin reproduces the
    %export functionality in the Labview Utility
    %'Export Scans To Spreadsheet.vi' in library 'sx-util.llb' from
    %Cryogenic. This particular plugin is configured for field sweeps, ie H
    %is the independent variable.
    
    %Note that scans will be split into up-and down-position-scans. Make
    %sure to tick the AverageConsecutive box in Postprocessing!
    
    methods (Access = protected)
        function [meta] = GetMetaData(this)
            meta.XVar = 'H';
            meta.CalibrationFactor = -2.28e-8;  %User to verify - data should scale onto data files produced by instrument
            meta.CoilRadius = 14.2;     %User should confirm these values for their system. Check the LabView.
            meta.CoilSeparation = 4.1;  %User should confirm these values for their system. Check the LabView.
            meta.CryostatInfo = 'Cryogenic Inc. S700X SQUID, .dat raw format, MvH';
        end
    end
    
    methods(Access = public)
        
        function [results, info] = process(this, fileName, scaleFactor)
            %Tell the logger we are busy importing, and start a diagnostics
            %timer.
            this.Logger.setBusy("import");
            t = tic();
                        
            %Read in the raw .dat file and parse into a 2D array
            rawdata = this.ReadRawFile(fileName);
            numberOfCols = size(rawdata, 2);
            
            %Count number of columns - we will have an unknown number of
            %Voltage columns (Column 5 onwards)
            data(:,1) = rawdata(:, 1); %Column 1 - Time
            data(:,2) = rawdata(:, 2); %Column 2 - Temperature
            data(:,3) = rawdata(:, 3); %Column 3 - Field
            data(:,4) = rawdata(:, 4); %Column 4 - Positions
                        
            %Average the scans columns
            for i = 1 : numberOfCols - 4
                scans(:,i) = rawdata(:, i + 4);
            end
            voltageAverage = mean(scans,2);  
            data(:, 5) = voltageAverage;
            
            %Work out how many points are in each scan
            pointsInScan = this.getNumberOfPointsInScan(data(:,4));
            
            %Number of scans
            numberOfScans = length(data(:,4)) / pointsInScan;
            
            % Allocate a 3D array to store data. This array will
            % eventually be [NumDataPointsPerScan x 2 x NumScans].
            % For every scan, there are NumDataPointsPerScan [position,
            % signal] pairs.
            scanData = nan(pointsInScan,2,numberOfScans);
            
            temperatures = nan(numberOfScans, 1);
            fields = nan(numberOfScans, 1);
            
            %Map the tabled data into the expected format in scanData
            for i = 1 : numberOfScans
                for j = 1 : pointsInScan
                    z = data((i-1) * pointsInScan + j, 4);
                    V = data((i-1) * pointsInScan + j, 5);
                    scanData(j, 1, i) = z*10; %Convert cm to mm
                    scanData(j, 2, i) = V * scaleFactor;
                end
                
                %Retrieve temperature and field data for this scan
                temperatures(i) = data((i-1)* pointsInScan+1, 2);
                fields(i) = data((i-1)* pointsInScan+1, 3);
            end
            
            time = toc(t);
            this.Logger.logInfo(sprintf("Imported %i scans in %.2f s.", numberOfScans, time));
            
            % Results to return.
            results.Temperatures = fields;
            results.Fields = temperatures;
            results.ScanData = scanData;
            
            % Diagnostics to return.
            info.FileName = fileName;
            info.NumScans = numberOfScans;
            info.TimeInSeconds = time;
            info.Meta = this.GetMetaData();
            
            this.Logger.setFinished("Import");
        end
    end
    
    methods(Access = protected)
        
        function pointsInScan = getNumberOfPointsInScan(~, positionsArray)  %positionsArray is a single column array of doubles
            %Position values in a single scan ramp up contiuously, then
            %back down to starting value. Look at data and see where they
            %reach the start value again - that's the start of a new scan
            initialPos = positionsArray(1);
            
            n = 2;
            while(initialPos ~= positionsArray(n))
                n = n +1;
            end
            
            pointsInScan = n/2; %Scans go up and down - let's split em in half
        end
        
        function dataArray = ReadRawFile(obj, filePath)
            % Open the file
            fileID = fopen("Sn.dat");
            
            %% Properties for reading the file
            size = [inf];
            precision = 'bit32'; % We read as bit32 not int32 such that skip values
            % are read in bits not bytes which we will want.
            skip = 0;
            machine = 'b'; % BIG-endian ordering. This is crucial and may not be the
            % system default.
            
            %% Number of scans and getting indexes
            
            % The first thing we want to read are 2 int32 values which tell us the
            % relevant size of the file. We expect [0 4096], 0 as it's a 1D array.
            lengths = (fread(fileID, 2, precision, skip, machine));
            
            % We should now be 2 int32 values, or 64 bits, or 8 bytes into the file
            % which we can check with ftell(fileID). It's important that we do not now
            % reset to the start of the file, as all the LabView we're translating
            % skips these values for everything it does.
            
            % What it does next is to continue reading from this point in the file,
            % still int32s, looking for the first occurence of zero. The number of
            % values read before this tells us how many scans (FULL scans up and down,
            % possibly repeated, which will eventually be a single point in MvT or MvH
            % etc.) are in the file... Well there are two more indexes than scans but
            % figuring that out now, first one seems to give header info and the final
            % one is also different. We read lenths(2) points into the file for some
            % reason.
            
            indexes = (fread(fileID, lengths(2), precision, skip, machine));
            
            firstZeroIndex = find(~indexes,1,'first');
            noOfIndexes = firstZeroIndex-1;
            
            % We can drop all the zeroes and ignore the first and last values. Maybe
            % there's a cleaner way to do this.
            indexes = indexes(1:noOfIndexes);
            indexes(1,:) = [];
            indexes(end,:) = [];
            noOfIndexes = noOfIndexes - 2;
            
            %% Reading scans
            
            % What indexes tells us is the bit position from the start of the file
            % from
            % which we read to access the raw data for each scan.
            setOfScans = cell(noOfIndexes,1);
            
            for i = 1:noOfIndexes
                
                fseek(fileID,indexes(i),'bof'); % Go to bit position index.
                fseek(fileID,8,'cof'); % Skip the 2 dimension numbers.
                
                setOfScans{i} = fread(fileID, lengths(2), precision, skip, machine);
                firstZeroIndexSoS = find(~setOfScans{i},1,'first');
                
                % The LabView actually runs functions on the the first and every other
                % value in this, so dump the rest.
                setOfScans{i} = setOfScans{i}(1:2:firstZeroIndexSoS-1);
                
            end
            
            %% Next steps
            
            % What we do next is TO ACTUALLY READ MEANINGFUL DATA. The values in
            % setOfScans{i}(1) contain the "before" values of time, temperature and
            % applied field, which are the values the LabView outputs.
            
            % Initialise a cell array to hold data.
            dataOut=cell(length(setOfScans), 1);
            
            for i = 1:length(setOfScans)
                
                % The first position of setOfScans gives infoamtion on time, temperature
                % and applied field. First get size data because why not?
                fseek(fileID, setOfScans{i}(1),'bof');
                metaSize = fread(fileID, [2], precision,skip,machine);
                
                % Read the metadata. Not very elegant.
                metaData = fread(fileID, metaSize(2), 'single', skip, machine);
                
                temperature = metaData(4);
                field = metaData(6);
                time = metaData(12);
                
                meta = [time temperature field];
                
                % The second position of setOfScans gives the actual measurement data. We
                % read first the scan dimensions (number of repeated scans and number of
                % points per scan), which we must rotate to get into the form needed for
                % main data import.
                fseek(fileID, setOfScans{i}(2),'bof');
                scanDimensions = rot90(fread(fileID, [2], 'bit32', skip, machine),3);
                
                % Read the scan data. The ' for transposing is important!
                dataOut{i,1} = fread(fileID, scanDimensions, 'single', skip, machine)';
                
                % Add in metadata to every line, to match how the LabView outputs (except
                % each scan is in its own cell).
                dataOut{i,1} = [repmat(meta, [scanDimensions(2), 1]) dataOut{i,1}];
                
            end
            
            % Put all the data together in a format like the LabView currently does.            
            dataArray = cell2mat(dataOut);
            
            %% Clean up
            fclose(fileID);
        end
        
    end
    
end