%-------------------------------------Licensing and fair use notice---------------------------------------
%---------------------------------------------------------------------------------------------------------
%This code file forms part of the SquidLab software, University of Warwick and University of Cambridge
%SquidLab remains the intellectual property of the Universities of Warwick and Cambridge, but is freely 
%distributed under an Academic Use license for non-commercial use. The license file is included with the 
%code files when downloaded, and must always be kept with them if distributed. Please also credit the 
%authors if the software contributes to any research results. Please read and make sure you agree with 
%the points in the (short) license document. In brief, you may use and also modify any of the code files 
%for non-commerical purposes, and should contact Warwick Ventures at the University of Warwick with any 
%questions as to potential commercial or profit-making use. 
%And remember, we can't guarantee that the software is bug or error free! Make sure to check any results.
%---------------------------------------------------------------------------------------------------------

classdef S700X_MvH < squidlab.import.ImportPipeline
    %Import pipeline for a file generated by a Cryogenic Inc. S700X
    %Magnetometer. The instrument generates binary files (.dat and .wat).
    %They must be converted to readable formats using the Labview Utility
    %'Export Scans To Spreadsheet.vi' in library 'sx-util.llb'
    %Note that scans will be split into up-and down-position-scans. Make
    %sure to tick the AverageConsecutive box in Postprocessing!
        
    methods (Access = protected)
        function [meta] = GetMetaData(this)
            meta.XVar = 'H';
            meta.CalibrationFactor = -2.28e-8;  %User to verify - data should scale onto data files produced by instrument
            meta.CoilRadius = 14.2;     %User should confirm these values for their system. Check the LabView.
            meta.CoilSeparation = 4.1;  %User should confirm these values for their system. Check the LabView.
            meta.CryostatInfo = 'Cryogenic Inc. S700X SQUID, .dat converted format, MvH';
        end
    end
    
    methods(Access = public)

        function [results, info] = process(this, fileName, scaleFactor)
            %Tell the logger we are busy importing, and start a diagnostics
            %timer.
            this.Logger.setBusy("import");
            t = tic();
            
            % Reads the data in the file fileName, and returns a
            % struct of scans, temperatures and fields, and a struct of
            % additional diagnostic.
            
            % Initialize variables.
            delimiter = ',';
            startRow = 1;
            endRow = inf; 
            
            %Read the first line (there should be no header unless User
            %added it manually!) and find number of columns.
            %File will be arranged (tab separated) as "Time
            %Temperature (Tb after)        Field(T)     Positions        1.Scan     2.Scan   .....    N.Scan"        
            [numberOfCols, formatSpec] = this.readFirstLineGetColNos(fileName);       
            
            % Open the text file again.
            fileID = fopen(fileName,'r');            
            
            % Read columns of data according to the format.
            textscan(fileID, '%[^\n\r]', startRow(1)-1, 'WhiteSpace', '', 'ReturnOnError', false);
            dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'TextType', 'string', 'EmptyValue', NaN, 'ReturnOnError', false, 'EndOfLine', '\r\n');
            for block=2:length(startRow)
                frewind(fileID);
                textscan(fileID, '%[^\n\r]', startRow(block)-1, 'WhiteSpace', '', 'ReturnOnError', false);
                dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'TextType', 'string', 'EmptyValue', NaN, 'ReturnOnError', false, 'EndOfLine', '\r\n');
                for col=1:length(dataArray)
                    dataArray{col} = [dataArray{col};dataArrayBlock{col}];
                end
            end
            
            % Close the text file.
            fclose(fileID);
            
            %Convert from wierd cell array into a double array. Also
            %average over the N scan columns at this stage.
            data(:,1) = dataArray{1};   %Time
            data(:,2) = dataArray{2};   %Temperature            
            data(:,3) = dataArray{3};   %Field
            data(:,4) = dataArray{4};   %Positions
            
            %Average the scans columns
            for i = 1 : numberOfCols - 4
                scans(:,i) = dataArray{i + 4};   
            end
            data(:,5) = mean(scans,2);  %Scans
                       
            %Work out how many points are in each scan
            pointsInScan = this.getNumberOfPointsInScan(data(:,4));
            
            %Number of scans
            numberOfScans = length(data(:,4)) / pointsInScan;
            
            % Allocate a 3D array to store data. This array will
            % eventually be [NumDataPointsPerScan x 2 x NumScans].
            % For every scan, there are NumDataPointsPerScan [position,
            % signal] pairs.
            scanData = nan(pointsInScan,2,numberOfScans);
            
            temperatures = nan(numberOfScans, 1);
            fields = nan(numberOfScans, 1);
            
            %Map the tabled data into the expected format in scanData
            for i = 1 : numberOfScans
                for j = 1 : pointsInScan
                    z = data((i-1) * pointsInScan + j, 4);
                    V = data((i-1) * pointsInScan + j, 5);
                    scanData(j, 1, i) = z*10; %Convert cm to mm    
                    scanData(j, 2, i) = V * scaleFactor;
                end
                
                %Retrieve temperature and field data for this scan
                temperatures(i) = data((i-1)* pointsInScan+1, 2);
                fields(i) = data((i-1)* pointsInScan+1, 3);
            end
            
            time = toc(t);
            this.Logger.logInfo(sprintf("Imported %i scans in %.2f s.", numberOfScans, time));
            
            % Results to return.
            results.Temperatures = fields;
            results.Fields = temperatures;
            results.ScanData = scanData;
            
            % Diagnostics to return.
            info.FileName = fileName;
            info.NumScans = numberOfScans;
            info.TimeInSeconds = time;
            info.Meta = this.GetMetaData();
            
            this.Logger.setFinished("Import");
        end
    end
    
    methods(Access = protected)
        
        function pointsInScan = getNumberOfPointsInScan(~, positionsArray)  %positionsArray is a single column array of doubles
            %Position values in a single scan ramp up contiuously, then
            %back down to starting value. Look at data and see where they
            %reach the start value again - that's the start of a new scan
            initialPos = positionsArray(1);
            
            n = 2;
            while(initialPos ~= positionsArray(n))
                n = n +1;
            end
            
            pointsInScan = n/2; %Scans go up and down - let's split em in half
        end    
        
        function [numberOfColumns, formatSpec] = readFirstLineGetColNos(obj, fileName)            
            % Open the text file.
            fileID = fopen(fileName,'r');
            
            %Read the first line. We need to work out how many columns we
            %have!
            %Note that if a user manually added a header line, that'll
            %break everything.. would need to add an 'fgetl' before this to
            %skip it..
            firstLine = fgetl(fileID);
            
            % Close the text file. Will be opened again for data reading.
            fclose(fileID);
            
            %File will be arranged (tab separated) as "Time
            %Temperature (Tb after)        Field(T)     Positions        1.Scan     2.Scan   .....    N.Scan"            
            cols = strsplit(firstLine, '\t');   
            numberOfColumns = length(cols);
            
            %Set up formatSpec based on number of columns
            formatSpec = '%f';
            for i = 2 : numberOfColumns
                formatSpec = [formatSpec '%f'];
            end
            formatSpec = [formatSpec '%[^\n\r]']; 
        end
        
    end
    
end